name: Manual Tests
on: [workflow_dispatch]
jobs:
  build:
    strategy:
            matrix:
              os: [ubuntu-latest]
              python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Run Test
        run: python -m unittest discover tests
      
      
